server:
  port: 0

spring:
  application:
    name: campain-web-services
  main:
    allow-bean-definition-overriding: true

  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
        - localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: promotion-full-consumer
      auto-offset-reset: earliest

  datasource:
    url: jdbc:postgresql://localhost:5432/mycampain
    username: campain-user
    password: dummypassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

logging:
  level:
    root: INFO
    org:
      apache:
        cxf:
          services: INFO
          interceptor: INFO
          interceptor.LoggingInInterceptor: INFO
          interceptor.LoggingOutInterceptor: INFO
          logging:
            enabled: INFO
